from django.db import models
from django.contrib.postgres.fields import JSONField
from timezone_field import TimeZoneField  


class GenderChoices(models.TextChoices):
    MALE = "Male"
    FEMALE = "Female"
    OTHER = "Other"


class ProviderTypeChoices(models.TextChoices):
    MD = "MD"
    PA = "PA"
    PSYD = "PSYD"
    LCSW = "LCSW"
    NP = "NP"
    NPS = "NP,S"
    RN = "RN"
    BHNP = "BHNP"
    FNP = "FNP"
    RD = "RD"
    NONE = "None"


class SpecialityChoices(models.TextChoices):
    SHAPEWEAR = "Shapewear"
    WEIGHT_LOSS = "Weight loss"
    ENDOCRINOLOGY = "Endocrinology"
    CARDIOLOGY = "Cardiology"
    ONCOLOGY = "Oncology"
    ORTHOPEDICS = "Orthopedics"
    PRIMARY_CARE = "Primary Care"
    ALLERGY_IMMUNOLOGY = "Allergy & Immunology"
    BEHAVIOR_HEALTH = "Behavior Health & Psychiatry"
    CONCIERGE_MEDICINE = "Concierge Medicine and Direct Primary Care"
    ANESTHESIOLOGY = "Anesthesiology"
    DERMATOLOGY = "Dermatology"
    EMERGENCY_MEDICINE = "Emergency Medicine"
    GASTROENTEROLOGY = "Gastroenterology"
    MULTI_SPECIALITY = "Multi-speciality"
    NEPHROLOGY = "Nephrology"
    OBSTETRICS_GYNECOLOGY = "Obstetrics/Gynecology"
    ENT = "Otolaryngology(ENT)"
    PAIN_MANAGEMENT = "Pain Management"
    PATHOLOGY = "Pathology"
    PEDIATRICS = "Pediatrics"
    PODIATRY = "Podiatry"
    PULMONOLOGY = "Pulmonology"
    RADIOLOGY = "Radiology"
    RHEUMATOLOGY = "Rheumatology"
    SLEEP_MEDICINE = "Sleep Medicine"
    SURGICAL_SPECIALTIES = "Surgical Specialties"
    URGENT_CARE = "Urgent Care"
    UROLOGY = "Urology"
    CARE_MANAGEMENT = "Care Management Company"


class RoleChoices(models.TextChoices):
    PRACTICE_ADMIN = "Practice Admin"
    CARE_MANAGER = "Care Manager"
    DIETICIAN = "Dietician"
    COUNSELOR = "Counselor"
    PHYSICAL_TRAINER = "Physical Trainer"
    NP = "Nurse Practitioners(NP)"
    PA = "Physician Assistant(PA)"
    RN = "Registered Nurse(RN)"
    LPN = "Licensed Practical Nurse(LPN)"
    CARE_COORDINATOR = "Care Coordinator"
    CLINICAL_SOCIAL_WORKER = "Clinical Social Workers"
    PHARMACIST = "Pharmacist"
    HEALTH_COACH = "Health Coach"
    CASE_MANAGER = "Case Manager"
    PHYSICIAN = "Physician"
    MD = "Medical Doctor(MD)"
    DO = "Doctor of Osteopathic Medicine(DO)"
    CNS = "Clinical Nurse Specialist(CNS)"
    CNM = "Certified Nurse Midwife(CNM)"
    PSYCHOLOGIST = "Clinical Psychologist(PsyD or PhD)"
    BILLING_ADMIN = "Billing Admin"
    CMA = "Certified Medical Assistant"


class StateChoices(models.TextChoices):
    ALABAMA = "Alabama"
    ALASKA = "Alaska"
    AMERICAN_SAMOA = "American Samoa"
    ARIZONA = "Arizona"
    ARKANSAS = "Arkansas"
    CALIFORNIA = "California"
    COLORADO = "Colorado"
    CONNECTICUT = "Connecticut"
    DELAWARE = "Delaware"
    DISTRICT_OF_COLUMBIA = "District Of Columbia"
    FEDERATED_STATES_OF_MICRONESIA = "Federated States Of Micronesia"
    FLORIDA = "Florida"
    GEORGIA = "Georgia"
    GUAM = "Guam"
    HAWAII = "Hawaii"
    IDAHO = "Idaho"
    ILLINOIS = "Illinois"
    INDIANA = "Indiana"
    IOWA = "Iowa"
    KANSAS = "Kansas"
    KENTUCKY = "Kentucky"
    LOUISIANA = "Louisiana"
    MAINE = "Maine"
    MARSHALL_ISLANDS = "Marshall Islands"
    MARYLAND = "Maryland"
    MASSACHUSETTS = "Massachusetts"
    MICHIGAN = "Michigan"
    MINNESOTA = "Minnesota"
    MISSISSIPPI = "Mississippi"
    MISSOURI = "Missouri"
    MONTANA = "Montana"
    NEBRASKA = "Nebraska"
    NEVADA = "Nevada"
    NEW_HAMPSHIRE = "New Hampshire"
    NEW_JERSEY = "New Jersey"
    NEW_MEXICO = "New Mexico"
    NEW_YORK = "New York"
    NORTH_CAROLINA = "North Carolina"
    NORTH_DAKOTA = "North Dakota"
    NORTHERN_MARIANA_ISLANDS = "Northern Mariana Islands"
    OHIO = "Ohio"
    OKLAHOMA = "Oklahoma"
    OREGON = "Oregon"
    PALAU = "Palau"
    PENNSYLVANIA = "Pennsylvania"
    PUERTO_RICO = "Puerto Rico"
    RHODE_ISLAND = "Rhode Island"
    SOUTH_CAROLINA = "South Carolina"
    SOUTH_DAKOTA = "South Dakota"
    TENNESSEE = "Tennessee"
    TEXAS = "Texas"
    UTAH = "Utah"
    VERMONT = "Vermont"
    VIRGIN_ISLANDS = "Virgin Islands"
    VIRGINIA = "Virginia"
    WASHINGTON = "Washington"
    WEST_VIRGINIA = "West Virginia"
    WISCONSIN = "Wisconsin"
    WYOMING = "Wyoming"

class LanguageChoices(models.TextChoices):
    AFRIKAANS = "Afrikaans"
    ARABIC = "Arabic"
    ALGERIAN_ARABIC = "Algerian Arabic"
    ASTURIAN = "Asturian"
    AZERBAIJANI = "Azerbaijani"
    BULGARIAN = "Bulgarian"
    BELARUSIAN = "Belarusian"
    BENGALI = "Bengali"
    BRETON = "Breton"
    BOSNIAN = "Bosnian"
    CATALAN = "Catalan"
    CZECH = "Czech"
    WELSH = "Welsh"
    DANISH = "Danish"
    GERMAN = "German"
    LOWER_SORBIAN = "Lower Sorbian"
    GREEK = "Greek"
    ENGLISH = "English"
    AUSTRALIAN_ENGLISH = "Australian English"
    BRITISH_ENGLISH = "British English"
    ESPERANTO = "Esperanto"
    SPANISH = "Spanish"
    ARGENTINIAN_SPANISH = "Argentinian Spanish"
    COLOMBIAN_SPANISH = "Colombian Spanish"
    MEXICAN_SPANISH = "Mexican Spanish"
    NICARAGUAN_SPANISH = "Nicaraguan Spanish"
    VENEZUELAN_SPANISH = "Venezuelan Spanish"
    ESTONIAN = "Estonian"
    BASQUE = "Basque"
    PERSIAN = "Persian"
    FINNISH = "Finnish"
    FRENCH = "French"
    FRISIAN = "Frisian"
    IRISH = "Irish"
    SCOTTISH_GAELIC = "Scottish Gaelic"
    GALICIAN = "Galician"
    HEBREW = "Hebrew"
    HINDI = "Hindi"
    CROATIAN = "Croatian"
    UPPER_SORBIAN = "Upper Sorbian"
    HUNGARIAN = "Hungarian"
    ARMENIAN = "Armenian"
    INTERLINGUA = "Interlingua"
    INDONESIAN = "Indonesian"
    IGBO = "Igbo"
    IDO = "Ido"
    ICELANDIC = "Icelandic"
    ITALIAN = "Italian"
    JAPANESE = "Japanese"
    GEORGIAN = "Georgian"
    KABYLE = "Kabyle"
    KAZAKH = "Kazakh"
    KHMER = "Khmer"
    KANNADA = "Kannada"
    KOREAN = "Korean"
    KYRGYZ = "Kyrgyz"
    LUXEMBOURGISH = "Luxembourgish"
    LITHUANIAN = "Lithuanian"
    LATVIAN = "Latvian"
    MACEDONIAN = "Macedonian"
    MALAYALAM = "Malayalam"
    MONGOLIAN = "Mongolian"
    MARATHI = "Marathi"
    MALAY = "Malay"
    BURMESE = "Burmese"
    NORWEGIAN_BOKMAL = "Norwegian Bokmål"
    NEPALI = "Nepali"
    DUTCH = "Dutch"
    NORWEGIAN_NYNORSK = "Norwegian Nynorsk"
    OSSETIC = "Ossetic"
    PUNJABI = "Punjabi"
    POLISH = "Polish"
    PORTUGUESE = "Portuguese"
    BRAZILIAN_PORTUGUESE = "Brazilian Portuguese"
    ROMANIAN = "Romanian"
    RUSSIAN = "Russian"
    SLOVAK = "Slovak"
    SLOVENIAN = "Slovenian"
    ALBANIAN = "Albanian"
    SERBIAN = "Serbian"
    SERBIAN_LATIN = "Serbian Latin"
    SWEDISH = "Swedish"
    SWAHILI = "Swahili"
    TAMIL = "Tamil"
    TELUGU = "Telugu"
    TAJIK = "Tajik"
    THAI = "Thai"
    TURKMEN = "Turkmen"
    TURKISH = "Turkish"
    TATAR = "Tatar"
    UDMURT = "Udmurt"
    UKRAINIAN = "Ukrainian"
    URDU = "Urdu"
    UZBEK = "Uzbek"
    VIETNAMESE = "Vietnamese"
    SIMPLIFIED_CHINESE = "Simplified Chinese"
    TRADITIONAL_CHINESE = "Traditional Chinese"


class AutoTimelogAsChoices(models.TextChoices):
    CALL_WITH_PATIENT = "Call with patient"
    EMAIL_SENT_TO_PATIENT = "Email sent to patient"
    TEXT_SMS_SENT_TO_PATIENT = "Text SMS sent to patient"
    INSTANT_CALL_TO_PATIENT = "Instant call to patient"
    SUBMISSION_OF_SCREENING_ASSESSMENT_OF_PATIENT = "Submission of screening assesment of patient"
    ASSESSMENT_SUBMISSION_OF_PATIENT = "Assesment submission of patient"
    ASSESSMENT_REVIEW_OF_PATIENT = "Assesment review of patient"
    ASSIGNED_ASSESSMENT_TO_PATIENT = "Assigned assesment to patient"
    CARE_PLAN_REVIEW_AND_SIGNOFF = "Care plan review and signoff"
    VITAL_REVIEW_FOR_DEVICE_READING_RECEIVED = "Vital review for Device reading received"
    CANCELLATION_OF_CALL = "Cancellation of call"
    CALL_RESCHEDULE_FOR_PATIENT = "Call Reschedule for patient"
    CALL_SCHEDULED_FOR_PATIENT = "Call Scheduled for patient"
    EDUCATIONAL_MATERIAL_ASSIGNED_TO_PATIENT = "Educational material assigned to patient"
    RESOLVED_ALERT_ASSIGNED = "Resolved alert assigned"
    ALERT_REASSIGNMENT_TO_CARE_GIVER = "Alert reassignment to care giver"
    RESOLVED_TASK_ASSIGNED = "Resolved task assigned"
    TASK_REASSIGNMENT_TO_CARE_GIVER = "Task reassignment to care giver"
    NEW_TASK_ASSIGNMENT_TO_CARE_GIVER = "New Task assignment to care giver"
    SEND_CARE_PLAN_TO_PATIENT = "Send Care plan to patient"
    MONTHLY_CARE_PLAN_REVIEW = "Monthly care plan review"
    UPDATE_PATIENT_CENTERED_CARE_PLAN = "Update-Patient centered care plan"
    PATIENT_CENTERED_CARE_PLAN_ASSIGNMENT = "Patient-Centered Care Plan Assignment"
    TEXT_MESSAGE_TO_CAREGIVER = "Text Message to Caregiver"
    TEXT_MESSAGE_TO_PATIENT = "Text Message to Patient"
    EMAIL_EDU_MATERIAL_TO_CAREGIVER = "E-mail Educational Material to Caregiver"
    EMAIL_EDU_MATERIAL_TO_PATIENT = "E-mail Educational Material to Patient"
    TEXT_MESSAGE_TO_PATIENT_2 = "Text message to patient"
    FOLLOWUP_AFTER_PATIENT_VISIT = "Follow-up after patient visit to emergency department/other health care facility"
    WEEKLY_CLINICAL_REVIEW = "Weekly Clinical Review"
    WEEKLY_CHART_REVIEW = "Weekly Chart Review"
    EMAIL_UPDATED_CAREPLAN_TO_CAREGIVER = "E-mail Updated Care-Plan to Caregiver"
    EMAIL_UPDATED_CAREPLAN_TO_PATIENT = "E-mail Updated Care-Plan to Patient"
    EMAIL_INITIAL_CAREPLAN_TO_CAREGIVER = "E-mail Initial Care-Plan to Caregiver"
    EMAIL_INITIAL_CAREPLAN_TO_PATIENT = "E-mail Initial Care-Plan to Patient"
    PERSONAL_CARE_MONITORING = "Personal care monitoring"
    STAFF_REVIEW_HOME_HEALTH_RECORDS = "Staff review of home health records"
    STAFF_REVIEW_CONSULT_NOTES = "Staff review of consult notes"
    SCREENING_REMINDER_CALL = "Screening Reminder Call"
    SCHEDULING_APPOINTMENTS = "Scheduling appointments/services"
    RISK_ASSESSMENT = "Risk Assessment"
    REVIEW_CONTINUATION_OF_CARE_DOCS = "Review Continuation of Care documents"
    REFERRALS = "Referrals"
    RECEIVED_REVIEWED_FAX = "Received/Reviewed Fax"
    PROVIDER_REVIEW_SKILLED_NURSING = "Provider review of skilled nursing"
    PROVIDER_REVIEW_PATIENT_MESSAGE = "Provider review of patient/family telephone message"
    PROVIDER_REVIEW_LABS_TESTS = "Provider review for labs/tests"
    PROVIDER_REVIEW_LAB_ORDERS = "Provider review for hlab orders"
    PROVIDER_REVIEW_HOSPITAL_RECORDS = "Provider review for hospital/facility records"
    PROVIDER_REVIEW_HOME_HEALTH_NOTES = "Provider review for Home Health notes"
    PROVIDER_REVIEW_CONSULT_NOTES = "Provider review for consult notes"
    PROVIDER_REVIEW_CARE_PLAN = "Provider review for care plan"
    PROVIDER_ORDER_REVIEW_XRAY = "Provider order/review for x-ray"
    PROVIDER_ORDER_REVIEW_PROCEDURE = "Provider order/review for procedure"
    PROVIDER_ORDER_LABS = "Provider order for Labs"
    PROVIDER_ORDER_HOME_HEALTH = "Provider order for Home Health"
    PROVIDER_ORDER_DME = "Provider order for DME"
    PRESCRIPTION_REFILLS = "Prescription Refills"
    PREPARE_SEND_FAX = "Prepare/Send Fax"
    PREAUTHORIZATION = "Preauthorization"
    PRE_ENROLLMENT_ENGAGEMENT = "Pre-Enrollment Engagement"
    POST_CALL_NOTES_ACTION_ITEMS = "Post Call Notes/Action Items"
    PORTAL_MESSAGING = "Portal Messaging"
    PHYSICAL_THERAPY_ORDERS = "Physical Therapy Orders"
    PHARMACY_CORRESPONDENCE = "Pharmacy Correspondence"
    PATIENT_FACILITY_FORMS = "Patient/Facility forms"
    PATIENT_CENTERED_CARE_PLAN = "Patient-Centered Care Plan"
    PATIENT_PREPARATION = "Patient Preparation"
    PATIENT_ASSESSMENT = "Patient Assessment"
    OTHERS_SEE_NOTES = "Others (see notes for details)"
    NOTES_RECONCILIATION = "Notes Reconciliation"
    NEW_PATIENT_PREPARATION = "New Patient preparation"
    MONTHLY_TEXT_MESSAGE_CAMPAIGN = "Monthly Text Message Campaign"
    MONTHLY_EMAIL_MESSAGE_CAMPAIGN = "Monthly Email Message Campaign"
    MONTHLY_CLINICAL_REVIEW = "Monthly Clinical Review"
    MONTHLY_CHART_REVIEW = "Monthly Chart Review"
    MEDICATION_RECONCILIATION = "Medication Reconciliation"
    MEDICAL_RECORDS_REQUEST = "Medical Records Request"
    LETTER_TO_PROVIDER = "Letter to Provider"
    LETTER_TO_PATIENT = "Letter to Patient"
    LETTER_TO_FAMILY_CAREGIVER = "Letter sent to Patient's Family or Caregiver"
    LAB_RESULTS_DISCUSSION_WITH_FAMILY = "Lab/testing results discussed with patient's Family or Caregiver"
    LAB_RESULTS_DISCUSSION_WITH_PATIENT = "Lab/testing results discussed with patient"
    LAB_RADIOLOGY_ORDERS = "Lab/Radiology orders"
    LAB_REMINDER_CALL = "Lab Reminder Call"
    INITIAL_PATIENT_CENTERED_CARE_PLAN = "Initial Patient-Centered Care Plan"
    INITIAL_ACTION_ITEMS = "Initial Action Items"
    HOME_HEALTH_HOSPICE_ORDERS = "Home Health/Hospice Orders"
    FORWARDING_RECORDS_TO_PROVIDER = "Forwarding records to other Provider"
    FOLLOWUP_WITH_PATIENT_TESTING = "Follow up with Patient testing"
    EPRESCRIBE = "ePrescribe"
    EMAIL_TO_FROM_FAMILY = "Email to/from Patient's Family or Caregiver"
    EMAIL_TO_PROVIDER = "Email to Provider"
    EMAIL_TO_PATIENT = "Email to Patient"
    EMAIL_FROM_PROVIDER = "Email from Provider"
    EMAIL_FROM_PATIENT = "Email from Patient"
    DISCUSSIONS_WITH_OTHER_PROVIDERS = "Discussions with other providers"
    BEHAVIORAL_HEALTH_SCREENING = "Behavioral Health Screening"
    DISCUSSION_WITH_FAMILY = "Discussion with Patient's Family or Caregiver"
    DIAGNOSIS_REVIEW = "Diagnosis Review"
    DAILY_CHART_REVIEW = "Daily Chart Review"
    CLINICAL_REVIEW = "Clinical Review"
    CARE_TEAM_MESSAGING = "Care Team Messaging/Communication"
    CARE_PLAN_RECONCILIATION = "Care Plan Reconciliation"
    CARE_COORDINATION = "Care Coordination"



class Provider(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=30, choices=GenderChoices)
    provider_type = models.CharField(max_length=200, choices=ProviderTypeChoices)
    speciality = models.CharField(max_length=400, choices=SpecialityChoices)

    role = models.CharField(max_length=100, choices=RoleChoices)
    secondary_role = models.CharField(max_length=100, choices=RoleChoices, blank=True, null=True)
    experience = models.PositiveIntegerField()
    NPI_number = models.CharField(max_length=50)
    email = models.EmailField(unique=True)

    language = models.CharField(max_length=150,choices=LanguageChoices)
    phone_number = models.CharField(max_length=15)
    state = models.CharField(max_length=200, choices=StateChoices)
    time_zone = TimeZoneField(default="US/Eastern")
    state_license_number = models.CharField(max_length=150)

    bio = models.TextField(blank=True, null=True)
    image = models.FileField(upload_to="provider_images/", blank=True, null=True)
    status = models.BooleanField(default=True)
    admin= models.BooleanField(default=False)
    auto_timelog = models.BooleanField(default=False)
    auto_timelog_as = models.CharField(max_length=400, choices=AutoTimelogAsChoices, blank=True, null=True)



    def __str__(self):
        return f"{self.first_name} {self.last_name}"
