# Generated by Django 5.2.8 on 2025-11-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_name', models.CharField(max_length=150)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=150)),
                ('interval', models.IntegerField()),
                ('device', models.CharField(choices=[('Blood Pressure Monitor', 'Blood Pressure Monitor'), ('Blood Glucose Monitor', 'Blood Glucose Monitor'), ('Continuos Glucose Monitor', 'Continuos Glucose Monitor'), ('Digital Thermometer', 'Digital Thermometer'), ('Pulse Oximeter', 'Pulse Oximeter'), ('Peak flow meter', 'Peak Flow Meter'), ('Spirometer', 'Spirometer'), ('Weight scale', 'Weight Scale')], max_length=150)),
                ('alert', models.BooleanField(default=False)),
                ('high_alert_hours', models.CharField(choices=[('00', 'H00'), ('01', 'H01'), ('02', 'H02'), ('03', 'H03'), ('04', 'H04'), ('05', 'H05'), ('06', 'H06'), ('07', 'H07'), ('08', 'H08'), ('09', 'H09'), ('10', 'H10'), ('11', 'H11')], max_length=30)),
                ('high_alert_minutes', models.CharField(choices=[('00', 'M00'), ('01', 'M01'), ('02', 'M02'), ('03', 'M03'), ('04', 'M04'), ('05', 'M05'), ('06', 'M06'), ('07', 'M07'), ('08', 'M08'), ('09', 'M09'), ('10', 'M10'), ('11', 'M11'), ('12', 'M12'), ('13', 'M13'), ('14', 'M14'), ('15', 'M15'), ('16', 'M16'), ('17', 'M17'), ('18', 'M18'), ('19', 'M19'), ('20', 'M20'), ('21', 'M21'), ('22', 'M22'), ('23', 'M23'), ('24', 'M24'), ('25', 'M25'), ('26', 'M26'), ('27', 'M27'), ('28', 'M28'), ('29', 'M29'), ('30', 'M30'), ('31', 'M31'), ('32', 'M32'), ('33', 'M33'), ('34', 'M34'), ('35', 'M35'), ('36', 'M36'), ('37', 'M37'), ('38', 'M38'), ('39', 'M39'), ('40', 'M40'), ('41', 'M41'), ('42', 'M42'), ('43', 'M43'), ('44', 'M44'), ('45', 'M45'), ('46', 'M46'), ('47', 'M47'), ('48', 'M48'), ('49', 'M49'), ('50', 'M50'), ('51', 'M51'), ('52', 'M52'), ('53', 'M53'), ('54', 'M54'), ('55', 'M55'), ('56', 'M56'), ('57', 'M57'), ('58', 'M58'), ('59', 'M59')], max_length=30)),
                ('medium_altert_hours', models.CharField(choices=[('00', 'H00'), ('01', 'H01'), ('02', 'H02'), ('03', 'H03'), ('04', 'H04'), ('05', 'H05'), ('06', 'H06'), ('07', 'H07'), ('08', 'H08'), ('09', 'H09'), ('10', 'H10'), ('11', 'H11')], max_length=30)),
                ('medium_alert_minutes', models.CharField(choices=[('00', 'M00'), ('01', 'M01'), ('02', 'M02'), ('03', 'M03'), ('04', 'M04'), ('05', 'M05'), ('06', 'M06'), ('07', 'M07'), ('08', 'M08'), ('09', 'M09'), ('10', 'M10'), ('11', 'M11'), ('12', 'M12'), ('13', 'M13'), ('14', 'M14'), ('15', 'M15'), ('16', 'M16'), ('17', 'M17'), ('18', 'M18'), ('19', 'M19'), ('20', 'M20'), ('21', 'M21'), ('22', 'M22'), ('23', 'M23'), ('24', 'M24'), ('25', 'M25'), ('26', 'M26'), ('27', 'M27'), ('28', 'M28'), ('29', 'M29'), ('30', 'M30'), ('31', 'M31'), ('32', 'M32'), ('33', 'M33'), ('34', 'M34'), ('35', 'M35'), ('36', 'M36'), ('37', 'M37'), ('38', 'M38'), ('39', 'M39'), ('40', 'M40'), ('41', 'M41'), ('42', 'M42'), ('43', 'M43'), ('44', 'M44'), ('45', 'M45'), ('46', 'M46'), ('47', 'M47'), ('48', 'M48'), ('49', 'M49'), ('50', 'M50'), ('51', 'M51'), ('52', 'M52'), ('53', 'M53'), ('54', 'M54'), ('55', 'M55'), ('56', 'M56'), ('57', 'M57'), ('58', 'M58'), ('59', 'M59')], max_length=30)),
            ],
        ),
    ]
