# Generated by Django 5.2.8 on 2025-11-13 12:03

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', timezone_field.fields.TimeZoneField(default='US/Eastern')),
                ('email_verify', models.BooleanField(default=False)),
                ('caller_id', models.CharField(max_length=150)),
                ('caller_id_verify', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('smtp', models.BooleanField(default=False)),
                ('alerts', models.BooleanField(default=False)),
            ],
        ),
    ]
