# Generated by Django 5.2.8 on 2025-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('SMS', 'Sms'), ('Email', 'Email'), ('Note', 'Note')], max_length=150)),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
