# Generated by Django 5.2.8 on 2025-11-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('patient_count', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
